config/routes.rb
Rails.application.routes.draw do
  
  get 'pages/home'

  devise_for :users, :controllers => {
                        :omniauth_callbacks => 'omniauth_callbacks',
                        :registrations => 'registrations'
                      }
  resources :users, only: [ :show ]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [ :create ]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get '/search' => 'pages#search'

  root 'pages#home'

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_leftnav.html.erb
<div class="list-group leftnav">
  <%= active_link_to "Your Rooms", rooms_path, class: 'list-group-item' %>
  <%= active_link_to "Your Reservations", your_reservations_path, class: 'list-group-item' %>
  <%= active_link_to "Your Trips", your_trips_path, class: 'list-group-item' %>
</div>

app/views/shared/_message.html.erb
<script type="text/javascript">
	toastr.options = {
	  "positionClass": "toast-top-center",
	}
</script>

<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
		<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
			toastr['<%= type %>']('<%= f[1] %>');
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-light bg-faded">
  <div class="container">
    <a class="navbar-brand" href="/">AirAlien</a>

    <div class="nav navbar-nav pull-xs-left">
      <%=	form_tag search_path, class: 'navbar-form navbar-left', method: :get do %>
        <%=	text_field_tag :search, params[:search], placeholder: 'Where are you going to?', class: 'form-control' %>
      <% end %>
    </div>

    <div class="nav navbar-nav pull-xs-right">
      <% if !user_signed_in? %>
        <%= link_to "Sign Up", new_user_registration_path, class: 'nav-item nav-link' %>
        <%= link_to "Login", new_user_session_path, class: 'nav-item nav-link' %>
      <% else %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag avatar_url(current_user), class: "avatar-small" %>
            <%= current_user.fullname %>
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <%= link_to "Your Listings", rooms_path, class: 'dropdown-item' %>
            <%= link_to "Your Reservations", your_reservations_path, class: 'dropdown-item' %>
            <%= link_to "Your Trips", your_trips_path, class: 'dropdown-item' %>
            <a class="dropdown-item" href="#">Wish Lists</a>
            <%= link_to "Edit Profile", edit_user_registration_path, class: 'dropdown-item' %>  
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Account Settings</a>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>  
          </div>
        </div>
      <% end %>

      <a href="" class="nav-item nav-link">
        <i class="fa fa-envelope-o"></i> Message
      </a>
      <a href="" class="nav-item nav-link">
        <i class="fa fa-home fa-lg"></i> Become a host
      </a>

    </div>
  </div>
</nav>